# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "lambda-sam-go-delve"

[default.build.parameters]
#cached = true
#parallel = true
parameter_overrides = "BuildCmd='GOARCH=amd64 GOOS=linux go build -gcflags=\"all=-N -l\" -o bootstrap dev-admin-func/main.go'"
#parameter_overrides = "BuildCmd='GOOS=darwin GOARCH=arm64 go build -gcflags=\"all=-N -l\" -o bootstrap dev-admin-func/main.go'"

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
debug_port = "5986"
debug_args = "-delveAPI=2"

[default.local_invoke]
[default.local_invoke.parameters]
debug_port = 5986
debug_args = "-delveAPI=2"
